# Generated by Django 5.0 on 2025-11-14 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('about', models.TextField(blank=True, verbose_name='О нас')),
                ('activities', models.TextField(blank=True, verbose_name='Направления деятельности')),
                ('volunteer_help', models.TextField(blank=True, verbose_name='Как помогают волонтёры')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('icon', models.CharField(default='🏢', max_length=10, verbose_name='Иконка')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
            ],
            options={
                'verbose_name': 'НКО',
                'verbose_name_plural': 'НКО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('organizer', models.CharField(max_length=200, verbose_name='Организатор')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('video', 'Видео'), ('document', 'Документ'), ('guide', 'Руководство'), ('presentation', 'Презентация')], max_length=20, verbose_name='Тип')),
                ('icon', models.CharField(default='📄', max_length=10, verbose_name='Иконка')),
                ('file', models.FileField(blank=True, upload_to='knowledge/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('icon', models.CharField(default='📰', max_length=10, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
